"""
cna_ssc/engine/piece_registry.py

Canonical registry of all 2,468 pieces in CNAv2.1.0.vmod.

Generated from buildFile.xml.  The ORDER of entries in PIECES is the
canonical variable ordering for the mixed-radix bijection.  It must never
change once established — reordering invalidates all encoded states.

Each piece entry:
    name     – Vassal entryName  (human-readable, unique enough)
    gpid     – Vassal global piece ID (integer string)
    image    – Primary image filename
    cat      – Category controlling which locations are valid:
                 'ground_unit'     : any hex + off-map supply zones
                 'aircraft'        : airfield hexes + air zones
                 'airfield_naval'  : any hex (airfield/naval counters)
                 'marker'          : any hex (admin markers)
                 'tracker'         : Game Track zone only
                 'weather'         : Weather Track zone only
                 'label'           : fixed (labels don't move)
    proto    – Vassal prototype name

Valid locations per category are defined in get_valid_locations().
"""

from __future__ import annotations
import json
import os
from typing import List, Dict, Tuple, Optional

from cna_ssc.engine.hex_grid import (
    ALL_LOCATIONS, HEX_POSITIONS, OFF_MAP_ZONE_NAMES,
    LOCATION_INDEX, N_ALL_LOCATIONS,
)

# ──────────────────────────────────────────────────────────────────────────────
# Piece data  (loaded from embedded JSON at import time)
# ──────────────────────────────────────────────────────────────────────────────

_RAW: List[Dict] = []

def _load() -> List[Dict]:
    """Load piece registry from embedded data or adjacent JSON file."""
    global _RAW
    if _RAW:
        return _RAW
    # Try to load from the JSON file (generated by buildfile_parser.py)
    here = os.path.dirname(os.path.abspath(__file__))
    json_path = os.path.join(here, "piece_registry_data.json")
    if os.path.exists(json_path):
        with open(json_path) as f:
            _RAW = json.load(f)
    else:
        raise FileNotFoundError(
            f"Piece registry data not found at {json_path}. "
            "Run: python -m cna_ssc.formats.buildfile_parser <buildFile.xml>"
        )
    return _RAW


# ──────────────────────────────────────────────────────────────────────────────
# Category → valid location set
# ──────────────────────────────────────────────────────────────────────────────

# Supply-related off-map zones where ground units can be
_GROUND_UNIT_OFFMAP = {
    "Sicily Holding Box",
    "Italy Holding Box",
    "Benghazi Holding Box",
    "Derna Holding Box",
    "Bardia Holding Box",
    "Tobruk Holding Box",
    "Alexandria Holding Box Hex 3613",
    "Alexandria Holding Box Hex 3714",
    "Tunis",
    "Gabes",
    "Tripoli",
    "Tripolitania",
    "Gabes-Tripoli",
    "Tripoli-Tripolitania",
    "Tripolitania-Nofilia",
    "OC",        # Organisation Chart — staging area
    "Axis Control",
    "Comm Control",
}

_AIRCRAFT_LOCATIONS = {
    "Sicily Holding Box",
    "Italy Holding Box",
    "Crete Holding Box",
    "Malta",
    "Map A", "Map B", "Map C", "Map D", "Map E",
    "Map D Operation Stage",
    "Map E Operation Stage",
    "German Shipping",
}

_NAVAL_LOCATIONS = {
    "Sicily Holding Box",
    "Italy Holding Box",
    "Crete Holding Box",
    "Malta",
    "Alexandria Holding Box Hex 3613",
    "German Shipping",
}

_TRACKER_LOCATIONS = {"Game Track"}
_WEATHER_LOCATIONS = {"Weather Track", "Map A Weather", "Map B Weather",
                      "Map C Weather", "Map D Weather", "Map E Weather"}
_FIXED_LOCATIONS   = {"OC"}  # labels / fixed pieces


def get_valid_locations(cat: str) -> List[str]:
    """Return ordered list of valid location IDs for a piece category.

    DESIGN NOTE: Only hex positions are used in the bijection.
    Off-map zones are excluded because their pixel coordinates overlap
    with playable map hexes, making zone→pixel→zone roundtrips unreliable.
    With ~4,959 hex positions per piece, the state space remains enormous
    (4959^187 ≈ 10^654) while eliminating any ambiguity.

    The list order is canonical — do not change once established.
    """
    # All mobile pieces: any valid hex position
    if cat in ("ground_unit", "aircraft", "airfield_naval", "marker"):
        return HEX_POSITIONS

    if cat == "tracker":
        return list(_TRACKER_LOCATIONS) or HEX_POSITIONS

    if cat == "weather":
        return list(_WEATHER_LOCATIONS) or HEX_POSITIONS

    if cat == "label":
        return list(_FIXED_LOCATIONS) or HEX_POSITIONS

    # fallback
    return HEX_POSITIONS


# ──────────────────────────────────────────────────────────────────────────────
# Public API
# ──────────────────────────────────────────────────────────────────────────────

class Piece:
    """Lightweight piece descriptor."""
    __slots__ = ("name", "gpid", "image", "cat", "proto",
                 "valid_locations", "_loc_index")

    def __init__(self, raw: Dict):
        self.name   = raw["name"]
        self.gpid   = raw["gpid"]
        self.image  = raw.get("image", "")
        self.cat    = raw.get("cat", "unknown")
        self.proto  = raw.get("proto", "")
        self.valid_locations: List[str] = get_valid_locations(self.cat)
        self._loc_index: Dict[str, int] = {
            loc: i for i, loc in enumerate(self.valid_locations)
        }

    @property
    def n_positions(self) -> int:
        """Radix for this piece in the mixed-radix encoding."""
        return len(self.valid_locations)

    def location_index(self, loc_id: str) -> int:
        """Return the index of loc_id in this piece's valid_locations list."""
        try:
            return self._loc_index[loc_id]
        except KeyError:
            raise ValueError(
                f"Location {loc_id!r} is not valid for piece {self.name!r} "
                f"(cat={self.cat})"
            )

    def __repr__(self) -> str:
        return f"<Piece {self.name!r} cat={self.cat} n_pos={self.n_positions}>"


# Piece list and lookup tables — populated lazily
_PIECES: Optional[List[Piece]] = None
_PIECE_BY_NAME: Optional[Dict[str, Piece]] = None
_PIECE_BY_GPID: Optional[Dict[str, Piece]] = None


def _ensure_loaded():
    global _PIECES, _PIECE_BY_NAME, _PIECE_BY_GPID
    if _PIECES is not None:
        return
    raw = _load()
    _PIECES = [Piece(r) for r in raw]
    _PIECE_BY_NAME = {p.name: p for p in _PIECES}
    _PIECE_BY_GPID = {p.gpid: p for p in _PIECES}


def pieces() -> List[Piece]:
    """Return the canonical ordered list of all pieces."""
    _ensure_loaded()
    return _PIECES          # type: ignore[return-value]


def piece_by_name(name: str) -> Piece:
    _ensure_loaded()
    return _PIECE_BY_NAME[name]   # type: ignore[index]


def piece_by_gpid(gpid: str) -> Piece:
    _ensure_loaded()
    return _PIECE_BY_GPID[gpid]   # type: ignore[index]


def total_pieces() -> int:
    return len(pieces())


# ──────────────────────────────────────────────────────────────────────────────
# Bijection dimensions
# ──────────────────────────────────────────────────────────────────────────────

def radix_list() -> List[int]:
    """Return list of radices (n_positions) for every piece, in canonical order."""
    return [p.n_positions for p in pieces()]


def state_space_size() -> int:
    """Total number of distinct states = ∏ p.n_positions for all pieces."""
    result = 1
    for r in radix_list():
        result *= r
    return result


def state_space_bits() -> float:
    import math
    return math.log2(state_space_size())


if __name__ == "__main__":
    import math
    ps = pieces()
    print(f"Total pieces:     {len(ps)}")
    print(f"State space bits: {state_space_bits():.0f}")
    print(f"Sample pieces:")
    for p in ps[:5]:
        print(f"  {p}")
